### ISSUE TITLE
Bug de lien 

### ISSUE THREAD

**Issue by allenshamal** [MineWeb/Theme-BlackFyre#1]
Les ":" n'apparaissent pas dans le lien de l'adresse du serveur vocal

![mineweb](https://user-images.githubusercontent.com/50488753/64951702-d3a81e00-d87e-11e9-939d-3d455f260e24.png)

1 : L'adresse que je la rentre dans le champ
2 : L'adresse comme elle apparait 
3 : Quand on clique dessus

**Comment by allenshamal** [comment]
Pour résoudre le problème il suffit de retirer le "http://" en début de lien et commencer par "discord.gg"

**Comment by sadoj-kuro** [comment]
ce bug n'est plus d'actualiter depuis 3 jours https://github.com/MineWeb/Theme-BlackFyre/commit/759563c3960951c5d3866580de9789fc2987310c

**Comment by allenshamal** [comment]
huumh pourtant j'avais encore le bug ce matin

**Comment by sadoj-kuro** [comment]
normal il faut mettre a jour le theme si déjà installer en effectuant un force update comme je n'est pas changer la version comme il n'y a que un seul modif

tonsite.fr/admin/theme/update/BlackFyre

**Comment by allenshamal** [comment]
Je ne savais pas ! pour "tonsite.fr/admin/theme/update/BlackFyre"
Je pensais que l'option de mise à jour du CMS mettais également à jour les thèmes. 

Merci pour l'info :)
